"""new fields in user model

Revision ID: 509d21d1eaff
Revises: f27d69e92758
Create Date: 2020-07-21 17:33:12.537645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509d21d1eaff'
down_revision = 'f27d69e92758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
